apiVersion: terraform.silvios.me/v1alpha1
kind: StackInstance
metadata:
  name: waspfiles
  namespace: default
spec:
  stack:
    provider: azurerm
    backend: azurerm
    registry: docker.io
    image: silviosilva/azure-bucket
    version: 0.1.2
  vars:
    resource_group_name: wasp
    name: waspfiles
    location: centralus
  outputs:
    - storage_account_id
    - primary_access_key
    - secondary_access_key
