#!/bin/bash
CRD_GROUP="terraform.silvios.me"

show_line() {
  MESSAGE=${1}
  OUTPUT=${2}

  echo "${MESSAGE}:"
  echo ""
  (bash -c "${OUTPUT}" 2>&1) | awk '{ print "  " $0 }'
  echo ""
}

show_line "Deployment"                                "kubectl get deploy -l app=terraform-controller"
show_line "Deployment PODs"                           "kubectl get pod -l app=terraform-controller"
show_line "CRDs for ${CRD_GROUP}"                     "kubectl api-resources | grep -E \"NAME|${CRD_GROUP}\""
show_line "StackInstance Objects"                     "kubectl get StackInstance --show-labels"
show_line "StackInstance Jobs"                        "kubectl get Job --show-labels"
show_line "StackInstance PODs"                        "kubectl get Pod --show-labels"
show_line "terraform-controller logs (last 50 lines)" "kubectl logs -l app=terraform-controller --tail 50"
