{{- if .Values.secrets.azurerm -}}
apiVersion: v1
kind: Secret
metadata:
  name: azurerm
  namespace: {{ .Values.secrets.azurerm.namespace }}
data:
  ARM_CLIENT_ID: {{ .Values.secrets.azurerm.data.clientId | b64enc }}
  ARM_CLIENT_SECRET: {{ .Values.secrets.azurerm.data.clientSecret | b64enc }}
  ARM_TENANT_ID: {{ .Values.secrets.azurerm.data.tenantId | b64enc }}
  ARM_KEYVAULT_NAME: {{ .Values.secrets.azurerm.data.keyVaultName | b64enc }}  
{{- end }}
