{{- if .Values.secrets.azurerm -}}
apiVersion: v1
kind: Secret
metadata:
  name: azurerm
  namespace: {{ .Values.secrets.azurerm.namespace }}
data:
  clientId: {{ .Values.secrets.azurerm.data.clientId | b64enc }}
  clientSecret: {{ .Values.secrets.azurerm.data.clientSecret | b64enc }}
{{- end }}
