---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payara-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: payara-operator-admin-cluster-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: payara-operator
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payara-operator
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: payara-operator
      containers:
        - name: operator
          image: silviosilva/payara-operator:latest
