apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-controller
  labels:
    app: terraform-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-controller
  template:
    metadata:
      labels:
        app: terraform-controller
    spec:
      serviceAccountName: terraform-controller
      containers:
        - name: controller
          image: docker.io/silviosilva/terraform-kubernetes-controller:latest
