---
apiVersion: silvios.me/v1
kind: PlatformInstance
metadata:
  name: global-1
spec:
  region: centralus
  provider: azure
---
apiVersion: silvios.me/v1
kind: PlatformInstance
metadata:
  name: global-2
spec:
  region: eastus2
  provider: azure
