#!/bin/bash
show_line() {
  MESSAGE=${1}
  OUTPUT=${2}

  echo "${MESSAGE}:"
  echo ""
  (bash -c "${OUTPUT}" 2>&1) | awk '{ print "  " $0 }'
  echo ""
}

show_line "StackInstance Resources"   "kubectl get StackInstance"
show_line "StackInstance POD"         "kubectl get Pod --show-labels"
show_line "StackInstances Events"     "kubectl describe StackInstances | tail -15"
#show_line "Container APPLY  logs"     "kubectl logs -l stack-instance-name=generic-bucket-1 -c apply  --tail 10"
#show_line "Container OUTPUT logs"     "kubectl logs -l stack-instance-name=generic-bucket-1 -c output --tail 10"
#show_line "StackInstance ConfigMap"   "kubectl get ConfigMap"
