#!/bin/bash
INSTANCE_NAME="${1}"

show_line() {
  MESSAGE=${1}
  OUTPUT=${2}

  echo "${MESSAGE}:"
  echo ""
  (bash -c "${OUTPUT}" 2>&1) | awk '{ print "  " $0 }'
  echo ""
}

show_line "${INSTANCE_NAME}"       "kubectl get StackInstance ${INSTANCE_NAME}"
show_line "StackInstance POD"      "kubectl get Pod --show-labels --selector stack-instance-name=${INSTANCE_NAME}"
#show_line "StackInstances Events"  "kubectl describe StackInstance ${INSTANCE_NAME} | grep 'Events:' -A 20"
#show_line "Container APPLY logs"   "kubectl logs --selector stack-instance-name=${INSTANCE_NAME} -c apply  --tail 10"
#show_line "Container OUTPUT logs"  "kubectl logs --selector stack-instance-name=${INSTANCE_NAME} -c output --tail 10"
show_line "ConfigMap"              "kubectl get ConfigMap ${INSTANCE_NAME}"
show_line "Secret"                 "kubectl get Secret    ${INSTANCE_NAME}"
