apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domains.poc.payara.fish
spec:
  group: poc.payara.fish
  names:
    kind: Domain
    listKind: DomainList
    plural: domains
    singular: domain
  scope: Namespaced
  versions:
    - name : v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                application-image:
                  type: string
                instance-image:
                  type: string
                application:
                  type: string
                instances:
                  type: integer
