apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: platforminstances.silvios.me
spec:
  group: silvios.me
  scope: Namespaced
  names:
    kind: PlatformInstance
    plural: platforminstances
    shortNames:
      - pis
      - pi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                provider:
                  type: string
            status:
              type: object
              properties:
                stackStatus:
                  type: string
      subresources:
        status: {}
