#!/bin/bash
CONTROLLER_IMAGE_NAME="silviosilva/terraform-kubernetes-controller"
CONTROLLER_VERSION=$(grep "version:" cz.yaml | awk '{ print $2 }' | tr -d " ")

CONTROLLER_IMAGE="${CONTROLLER_IMAGE_NAME?}:${CONTROLLER_VERSION?}"
CONTROLLER_IMAGE_LATEST="${CONTROLLER_IMAGE_NAME?}:latest"

sed -i "/^appVersion:/ s/appVersion.*/appVersion: ${CONTROLLER_VERSION?}/" manifests/charts/terraform-controller/Chart.yaml

mvn package && \
docker build \
  --rm \
  --tag "${CONTROLLER_IMAGE?}" \
  --tag "${CONTROLLER_IMAGE_LATEST?}" . && \

docker push "${CONTROLLER_IMAGE?}" && \
docker push "${CONTROLLER_IMAGE_LATEST?}"
