#!/bin/bash
create_cluster() {
  KIND_CLUSTER_NAME="trash" && \
  kind create cluster \
    --config "kind-cluster-config.yaml" \
    --name "${KIND_CLUSTER_NAME?}" && \
  for NODE in $(kubectl get nodes --output name); do
    kubectl wait ${NODE} \
      --for condition=Ready \
      --timeout=360s
  done && \
  kubectl config get-contexts
}
time create_cluster
