#!/bin/bash
KIND_CLUSTER_CONFIG_FILE="/tmp/kind-cluster-config.yaml"
cat <<EOF > "${KIND_CLUSTER_CONFIG_FILE}"
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
EOF

create_cluster() {
  KIND_CLUSTER_NAME="trash" && \
  kind create cluster \
    --config "${KIND_CLUSTER_CONFIG_FILE}" \
    --name "${KIND_CLUSTER_NAME?}" && \
  for NODE in $(kubectl get nodes --output name); do
    kubectl wait ${NODE} \
      --for condition=Ready \
      --timeout=360s
  done && \
  kubectl config get-contexts
}
time create_cluster
