#!/bin/bash
install() {
  helm repo add external-secrets https://external-secrets.github.io/kubernetes-external-secrets/ && \
  HELM_CHART_NEWEST_VERSION=$(helm search repo external-secrets -l | sed 1d | awk '{ print $2}' | sort --version-sort | tail --lines 1) && \
  echo "${HELM_CHART_NEWEST_VERSION}" && \
  helm install external-secrets external-secrets/kubernetes-external-secrets \
  --create-namespace \
  --namespace external-secrets \
  --version "${HELM_CHART_NEWEST_VERSION?}" \
  --wait
}
time install
