#!/bin/bash
CRD_GROUP="terraform.silvios.me"

show_line() {
  MESSAGE=${1}
  OUTPUT=${2}

  echo "${MESSAGE}:"
  echo ""
  (bash -c "${OUTPUT}" 2>&1) | awk '{ print "  " $0 }'
  echo ""
}

show_line "StackInstance Objects"     "kubectl get StackInstance --show-labels"
#show_line "StackInstance ConfigMap"   "kubectl get ConfigMap africa-1 -o json | jq .data | grep TF_VAR"
show_line "StackInstance POD"         "kubectl get Pod --show-labels"
#show_line "Container APPLY  logs"     "kubectl logs -l stack-instance-name=africa-1 -c apply  --tail 10"
show_line "Container OUTPUT logs"     "kubectl logs -l job-name=azure-example --tail 20"
show_line "Describe POD"              "kubectl describe pod | tail -20"
