---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-example
  namespace: default
data:
  TF_VAR_region: centralus
  STACK_INSTANCE_NAME: blue
---
apiVersion: batch/v1
kind: Job
metadata:
  name: azure-example
spec:
  template:
    spec:
      initContainers:
        - name: plan
          image: silviosilva/azure-example:0.1.0
          args: ["plan", "-no-color", "-input=false"]
          envFrom:
            - secretRef:
                name: azure-credentials
            - configMapRef:
                name: azure-example
        - name: apply
          image: silviosilva/azure-example:0.1.0
          args: ["apply", "-auto-approve", "-input=false", "-no-color"]
          envFrom:
            - secretRef:
                name: azure-credentials
            - configMapRef:
                name: azure-example
      containers:
        - name: output
          image: silviosilva/azure-example:0.1.0
          args: ["output", "-json"]
          envFrom:
            - secretRef:
                name: azure-credentials
            - configMapRef:
                name: azure-example
          env:
            - name: DEBUG
              value: "0"
      restartPolicy: Never
  backoffLimit: 2
