{{- range $instance := .Values.instances }}
---
apiVersion: terraform.silvios.me/v1
kind: StackInstance
metadata:
  name: {{ $instance.name }}
spec:
  stack:
    provider: google
    registry: docker.io/silviosilva
    image: bucket
    version: 0.1.0
  vars:
    name: {{ $instance.name }}
    location: {{ $instance.location }}
  outputs:
    - bucket_id
{{- end }}
