apiVersion: v1
kind: Pod
metadata:
  name: google-bucket-example
  namespace: default
spec:
  initContainers:
    - name: apply
      image: silviosilva/google-bucket:0.1.0
      args: ["apply", "-auto-approve", "-no-color"]
      envFrom:
        - secretRef:
            name: google-credentials
        - configMapRef:
            name: generic-bucket-1
      env:
        - name: DEBUG
          value: "1"
  containers:
    - name: output
      image: silviosilva/google-bucket:0.1.0
      args: ["plan", "-no-color"]
      envFrom:
        - secretRef:
            name: google-credentials
        - configMapRef:
            name: generic-bucket-1
  restartPolicy: OnFailure
